### ISSUE TITLE
v2.0.0 Umbrella

### ISSUE THREAD

**Issue by danez** [webpack-contrib/grunt-webpack#89]
- [ ] Improve docs (maybe section on webpack site?)
- [ ] Update/Correct Readme
- [ ] Add more examples
- [ ] Try getting a fix for circular references (https://github.com/gruntjs/grunt/issues/1560)
- [x] Create migration guide 1.0 -> 2.0
- [x] ~~Maybe change node support from >=4 back to >=0.10 because webpack2 seems it still has >=0.6~~
